version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: selestino  # Correct database name
      POSTGRES_USER: selestino_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d selestino -U selestino_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: selestino_user
      DB_PASSWORD: your_password
      DB_NAME: selestino  # Must match POSTGRES_DB

volumes:
  postgres_data:
