version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: selestino
      POSTGRES_USER: selestino_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d selestino -U selestino_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      discovery.type: single-node
    ports:
      - "9201:9200"  # Use 9201 on the host and map it to 9200 in the container

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8082:8080"  # Change host port to 8082 to avoid conflict
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  app:
    build: .
    ports:
      - "8081:8080"  # Change host port to 8081 to avoid conflict
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      elasticsearch:
        condition: service_started
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: selestino_user
      DB_PASSWORD: your_password
      DB_NAME: selestino
      REDIS_ADDR: redis:6379
      ELASTICSEARCH_URL: http://elasticsearch:9200  # This remains unchanged since it's the internal container port

volumes:
  postgres_data:
  jenkins_home:
