version: '3.8'

services:
  web:
    build: .
    command: bash -c "./wait-for-it.sh db && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - selestino-network  # Add the web service to the custom network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - selestino-network  # Add the db service to the custom network

volumes:
  postgres_data:

networks:
  selestino-network:  # Define a custom network for the services
    driver: bridge
