# k8s/selestino-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: selestino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selestino
  template:
    metadata:
      labels:
        app: selestino
    spec:
      containers:
        - name: selestino
          image: selestino:latest
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: selestino_user
            - name: DB_PASSWORD
              value: your_password
            - name: DB_NAME
              value: selestino
            - name: JWT_SECRET_KEY
              value: my_secret_key
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: selestino
spec:
  selector:
    app: selestino
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
