
services:
  web:
    build: .
    command: gunicorn selestino.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
    env_file: .env
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/var/www/html/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: selestino
      POSTGRES_USER: josuejero
      POSTGRES_PASSWORD: peruano1
    ports:
      - "5432:5432"

volumes:
  static_volume:
  postgres_data:
