---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - nodes
      - services
      - endpoints
      - nodes/proxy
      - nodes/metrics
    verbs:
      - get
      - list
      - watch
  # Add other necessary rules here

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-operator
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator
subjects:
  - kind: ServiceAccount
    name: prometheus-operator
    namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometheus-operator
  template:
    metadata:
      labels:
        name: prometheus-operator
    spec:
      serviceAccountName: prometheus-operator
      containers:
        - name: prometheus-operator
          image: quay.io/prometheus-operator/prometheus-operator:v0.50.0
          args:
            - --kubelet-service=kube-system/kubelet
            - --config-reloader-image=quay.io/prometheus-operator/prometheus-config-reloader:v0.50.0
            - --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.50.0
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
  # Add other necessary configurations here

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator
  namespace: default
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: prometheus-operator
