apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: selestino-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: selestino-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
