apiVersion: apps/v1
kind: Deployment
metadata:
  name: selestino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selestino
  template:
    metadata:
      labels:
        app: selestino
    spec:
      containers:
        - name: selestino
          image: josuejero/selestino:latest
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: selestino_user
            - name: DB_PASSWORD
              value: your_password
            - name: DB_NAME
              value: selestino
            - name: JWT_SECRET_KEY
              value: my_secret_key
            - name: REDIS_ADDR
              value: redis:6379
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch:9200
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.25"
            limits:
              memory: "1Gi"
              cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: selestino
spec:
  type: NodePort
  selector:
    app: selestino
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000  # You can choose any available node port between 30000-32767

